### PR TITLE
Add slack and telegram chat

### PR DESCRIPTION
**Pull request by vodniciarv**
Add slack and telegram chat link

### CODE REVIEW

**Comment by daffl** [comment]
Thank you @vodniciarv. I think having it on the main repository at `feathersjs/feathers` and adding it to https://docs.feathersjs.com/help/readme.html should be good. I should probably take the Slack links out of the other repositories.

**Comment by vodniciarv** [comment]
OK :)

**Comment by daffl** [comment]
Would you mind adding it to the help page though? Thank you!

**Comment by vodniciarv** [comment]
Yes, of course.

**Comment by vodniciarv** [comment]
Done!

**Pull request closed without merging**
